[tool.poetry]
name = "Authl"
version = "0.5.0"
description = "Framework-agnostic authentication wrapper"
authors = ["fluffy <fluffy@beesbuzz.biz>"]
license = "MIT"
readme = "README.md"
homepage = "https://plaidweb.site/"
repository = "https://github.com/PlaidWeb/Authl"
documentation = "https://authl.readthedocs.io/"

[tool.poetry.dependencies]
python = "^3.6"
beautifulsoup4 = "^4.9.1"
expiringdict = "^1.2.1"
itsdangerous = "^1.1.0"
requests = "^2.24.0"
requests_oauthlib = "^1.3.0"
validate_email = "^1.3"
mf2py = "^1.1.2"
"mastodon.py" = "^1.5.1"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.3"
flake8 = "^3.8.3"
flask = "^1.1.2"
isort = "^4"
mypy = "^0.782"
pylint = "^2.5.3"
coverage = "^5.2"
pytest = "^5.4.3"
requests-mock = "^1.8.0"
sphinx = "^3.1.2"
pytest-mock = "^3.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
