[tool.poetry]
name = "Authl"
version = "0.6.1"
description = "Framework-agnostic authentication wrapper"
authors = ["fluffy <fluffy@beesbuzz.biz>"]
license = "MIT"
readme = "README.md"
homepage = "https://plaidweb.site/"
repository = "https://github.com/PlaidWeb/Authl"
documentation = "https://authl.readthedocs.io/"

[tool.poetry.dependencies]
python = "^3.8.1"
beautifulsoup4 = "^4.9.1"
expiringdict = "^1.2.1"
itsdangerous = ">=1.1.0"
requests = "^2.24.0"
requests_oauthlib = "^1.3.0"
validate_email = "^1.3"
mf2py = "^1.1.2"
"mastodon.py" = "^1.5.1"
mastodon-py = "^1.7.0"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.0"
flake8 = "^6.0.0"
flask = "^2.2.2"
isort = "^5.10.1"
mypy = "^0.991"
pylint = "^2.15.6"
coverage = "^6.5.0"
pytest = "^7.2.0"
requests-mock = "^1.10.0"
sphinx = "^5.3.0"
pytest-mock = "^3.10.0"
gunicorn = "^20.1.0"
types-requests = "^2.28.11.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
