[tool.poetry]
name = "Authl"
version = "0.4.0post1"
description = "Genericized multi-protocol authentication wrapper"
authors = ["fluffy <fluffy@beesbuzz.biz>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/PlaidWeb/Authl"

[tool.poetry.dependencies]
python = "^3.5"
beautifulsoup4 = "^4.9.1"
expiringdict = "^1.2.1"
itsdangerous = "^1.1.0"
read_only_property = "^0.1"
requests = "^2.24.0"
requests_oauthlib = "^1.3.0"
validate_email = "^1.3"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.3"
flake8 = "^3.8.3"
flask = "^1.1.2"
isort = "^4"
mypy = "^0.782"
pylint = "^2.5.3"
coverage = "^5.2"
pytest = "^5.4.3"
requests-mock = "^1.8.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
